name: CI
on:
  push:
    branches:
      - "*/*"
      - "!main"
      - "!develop"

jobs:
  ci:
    name: CI - Test React Viper UI components
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.Js
        uses: actions/setup-node@v4
        with:
          node-version: '>=20.12.0'
      - name: Yarn Cache
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Make bash Scripts Executable
        run: chmod +x ./.github/bin/*.sh

      - name: Clear Yarn Cache
        run: yarn cache clean

      - name: Install
        run: ./.github/bin/ci_install.sh

      - name: Test components
        run: ./.github/bin/ci_test.sh
